#pragma once

#define IDC_STATIC              -1
#define IDD_CONFIG              101
#define IDC_SPEED_SLIDER        1001
#define IDC_DENSITY_SLIDER      1002
#define IDC_FONTSIZE_SLIDER     1003
#define IDC_HUE_SLIDER          1004
#define IDC_FONT_COMBO          1005
#define IDC_BOLD_CHECK          1006
#define IDC_RANDOMIZE_CHECK     1007
#define IDC_MASK_PATH           1008
#define IDC_BROWSE_MASK         1009
#define IDC_CLEAR_MASK          1010
#define IDC_USE_CUSTOM_WORD     1011
#define IDC_CUSTOM_WORD_EDIT    1012
#define IDC_SEQUENTIAL_CHECK    1013
#define IDC_SHOW_MASK_BG        1014
#define IDC_MASK_OPACITY_SLIDER 1015
#define IDC_WHITE_HEAD_CHECK    1016
#define IDC_MESSAGE_SPEED_SLIDER 1017
#define IDC_FADE_RATE_SLIDER    1018
#define IDC_DEPTH_RANGE_SLIDER  1019
#define IDC_ENABLE_3D_CHECK     1020
#define IDC_VARIABLE_FONT_CHECK 1021

// Performance optimization controls
#define IDC_ENABLE_BATCH_RENDERING    1022
#define IDC_ENABLE_FRAME_LIMITING     1023
#define IDC_TARGET_FPS_SLIDER         1024
#define IDC_ENABLE_ADAPTIVE_VSYNC     1025
#define IDC_SHOW_PERFORMANCE_METRICS  1026
#define IDC_ENABLE_DIRTY_RECTANGLES   1027

// Advanced feature controls  
#define IDC_ENABLE_LOGGING            1028
#define IDC_ENABLE_MOTION_BLUR        1029
#define IDC_ENABLE_PARTICLE_EFFECTS   1030
#define IDC_ENABLE_AUDIO_VISUALIZATION 1031

// Quality setting controls
#define IDC_ENABLE_HIGH_QUALITY_TEXT  1032
#define IDC_ENABLE_ANTI_ALIASING      1033

// Visual enhancement controls
#define IDC_VARIABLE_LEAD_SIZE         1036
#define IDC_ENABLE_CHARACTER_MORPHING 1037
#define IDC_ENABLE_PHOSPHOR_GLOW      1038
#define IDC_ENABLE_GLITCH_EFFECTS     1039
#define IDC_ENABLE_RAIN_VARIATIONS    1040
#define IDC_ENABLE_SYSTEM_DISRUPTIONS 1041
#define IDC_ENABLE_MOTION_REDUCTION   1042
#define IDC_ENABLE_CHARACTER_VARIETY  1043
#define IDC_MORPH_FREQUENCY_SLIDER    1044
#define IDC_MORPH_SPEED_SLIDER        1045
#define IDC_GLITCH_FREQUENCY_SLIDER   1046
#define IDC_GLOW_INTENSITY_SLIDER     1047
#define IDC_LATIN_CHAR_PROB_SLIDER    1048
#define IDC_SYMBOL_CHAR_PROB_SLIDER   1049

// Color preview panel
#define IDC_COLOR_PREVIEW_PANEL       1054

// Group boxes for organization
#define IDC_PERFORMANCE_GROUP         1050
#define IDC_ADVANCED_GROUP            1051
#define IDC_QUALITY_GROUP             1052
#define IDC_VISUAL_ENHANCEMENT_GROUP  1053
